# Generated by Django 5.0 on 2023-12-27 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tovar',
            name='price',
            field=models.CharField(max_length=10),
        ),
    ]
